### ISSUE TITLE
Any other requirements?

### ISSUE THREAD

**Issue by Nullsloth** [Icydeath/ffxi-addon-manager#2]
Recently did a fresh install of W11 and XI/Windower and can't get gui program to work anymore. Crashes as soon as I add windower directory. Is there any file requirements? When I tried to use it without GUI get an error saying its not able to find autoload.txt which is usually named after windower profiles and doesn't have file there made one and says it still cant find it.

**Comment by Icydeath** [comment]
It's trying to find the autoload.txt in the "Windower4\scripts\autoload" folder.
Check that folder to see if it exists.

**Comment by Nullsloth** [comment]
The folder itself does, but not the autoload.txt in the folder. It has my Main.txt and mule.txt windower profiles. I tried to copy a profile and rename to autoload.txt, but didn't work. I also tried to just make a txt file named autoload.txt aswell.

**Comment by Icydeath** [comment]
I mean every windower4 install should have autoload.txt file in the scripts\autoload folder

If yours doesn't then I'm not sure what is going on...
I guess lets start simple, are you running the program as administrator? (Right click the exe and select Run as Admin...)

Example of what the file should have in it below:
`
// !!! DO NOT EDIT !!!
// ==========================================================================
// This file is automatically generated. Any changes made to this file will
// be overwritten the next time Windower is run.
// 
// Please use the Windower plugin manager to edit your plugin autoload
// settings, and place any other initialization in scripts/init.txt.
// ==========================================================================
// !!! DO NOT EDIT !!!

wait 5;
load LuaCore;
load Config;
exec init.txt;
`
